Iter9
AlexBlackNn/metrics pull request #11
Opened 2024-06-30 11:08 UTC by AlexBlackNn

2024-07-03 12:12 UTC, tmvrus requested changes
есть вопросы

2024-07-03 12:12 UTC, tmvrus commented on app/agent/restagentsender/v2/sender.go
> +					if savedMetric.GetType() == "counter" {
строка "counter" довольно часто встречается в проекте, это хороший повод сделать ее константой

2024-07-03 12:12 UTC, tmvrus commented on app/agent/restagentsender/v2/sender.go
> +			<-time.After(time.Duration(mhs.cfg.ReportInterval) * time.Second)
значение `time.Duration(mhs.cfg.ReportInterval) * time.Second` будет вычислятся на каждой итерации цикла, можно вычислить один раз перед его началом

2024-07-03 12:12 UTC, tmvrus commented on app/agent/restagentsender/v2/sender.go
> +						SetRetryMaxWaitTime(time.Duration(mhs.cfg.AgentRetryMaxWaitTime) * time.Second)
эти два таймаута можно было вычислить один раз при создании кофига

2024-07-03 12:12 UTC, tmvrus commented on app/agent/restagentsender/v2/sender.go
> +				go func(savedMetric models.MetricInteraction) {
у этого подхода есть недостаток, что если горутины не будут успевать выполняться за `mhs.cfg.ReportInterval`?  есть шанс что клиент просто будет штормить сервис запросами  которые тот не успевает отрабатывать, рекомендую подумать о том как этого избежать

2024-07-03 12:12 UTC, tmvrus commented on cmd/server/main_test.go
> +//func (ms *MetricsSuite) TestServerGetAllMetricsHappyPath() {
закоменчеого кода в проекте быть не должно, он зашумляет проект и усложняет чтение

2024-07-03 12:12 UTC, tmvrus commented on internal/config/configserver/config.go
> +// Config consists project settings
а Go принято ставить точки в конце комментария
https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/bufio/scan.go;l=293

2024-07-03 12:12 UTC, tmvrus commented on internal/config/configserver/config.go
> +	}
если случилась какая-то другая ошибка?

2024-07-03 12:12 UTC, tmvrus commented on internal/config/configserver/config.go
> +		return &Config{}, config.ErrReadConfigFailed
возвращать значение вместе с ошибкой это некий мис-паттерн что ли, по крайне мере я такого нигде не встречал

2024-07-03 12:12 UTC, tmvrus commented on internal/handlers/v2/metrics_handlers.go
> +	ctx := context.Background()
а зачем брать пустой контекст если есть входящий запрос?

2024-07-03 12:12 UTC, tmvrus commented on internal/handlers/v2/metrics_handlers.go
> +	ctx := context.Background()
тот же самый вопрос про контекст что и выше

2024-07-03 12:12 UTC, tmvrus commented on pkg/storage/memstorage/gob_state_manager.go
> +		_ = file.Close()
ошибка не обрабатывается

2024-07-03 12:12 UTC, tmvrus commented on pkg/storage/memstorage/gob_state_manager.go
> +		_ = file.Close()
ошибка не обрабатывается

2024-07-03 12:12 UTC, tmvrus commented on pkg/storage/memstorage/mem_storage.go
> +var ErrFailedToRestoreMetrics = errors.New("failed to restore metrics")
обычно такого рода ошибки добавляют что бы используя их через errors.Is принимать какие-то решения, тут не оч ясно зачем была создана кастомная ошибка

2024-07-03 12:12 UTC, tmvrus commented on pkg/storage/memstorage/mem_storage.go
> +				<-time.After(time.Duration(cfg.ServerStoreInterval) * time.Second)
можно было интервал вычислить один раз перед началом цикла

2024-07-03 12:12 UTC, tmvrus commented on pkg/storage/memstorage/mem_storage.go
> +		_ = memStorage.jm.restoreMetrics()
ошибка не обрабатывается

2024-07-03 12:12 UTC, tmvrus commented on pkg/storage/memstorage/mem_storage.go
> +				<-memStorage.saveChan
а зачем такая сложная схема с каналом? запрос ведь все равно выполняется синхронно, так почему снаружи прост не дергать метод который все сохранит и обработает ошибку(которая сейчас никак не обрабатывается)?

тогда горутину можно будет вообще не запускать или интервал нулевой,  и код будет выглядет более выразително

2024-07-03 12:12 UTC, tmvrus commented on internal/handlers/v2/metrics_handlers_response.go
> +}
то что идет после тега validate по большому счету является бизнес-правилом, а для него нужны тесты

2024-07-03 12:12 UTC, tmvrus commented on internal/handlers/v2/metrics_handlers.go
> +		if errors.Is(err, io.EOF) {
ты довольно странную ситуацию хочешь тут обработать, не уверен что такое вообще может быть 
https://play.golang.com/p/CUzKzu7sfmL

2024-07-03 18:01 UTC, AlexBlackNn commented on app/agent/restagentsender/v2/sender.go
> +					if savedMetric.GetType() == "counter" {
Сделал. А есть смысл? "counter" - общепринятый тип метрики. Соответственно, можно ожидать, что он будет неизменен с течением времени.

2024-07-03 18:18 UTC, AlexBlackNn commented on app/agent/restagentsender/v2/sender.go
> +			<-time.After(time.Duration(mhs.cfg.ReportInterval) * time.Second)
Done

2024-07-03 18:32 UTC, AlexBlackNn commented on app/agent/restagentsender/v2/sender.go
> +						SetRetryMaxWaitTime(time.Duration(mhs.cfg.AgentRetryMaxWaitTime) * time.Second)
1. я их вынес из цикла. Теперь они будут вычисляться 1 раз. 
2. В конфиге я бы мог сделать так 
```
type Config struct {
...
  AgentRetryWaitTime    time.Duration  `yaml:"agent_retry_wait_time" env-default:"30s" env:"AGENT_RETRY_WAIT_TIME" envDefault:"30s"`
  AgentRetryMaxWaitTime time.Duration  `yaml:"agent_retry_max_wait_time" env-default:"90s" env:"AGENT_RETRY_MAX_WAIT_TIME" envDefault:"90s"`
...
}
```
Но с флагами, как быть? Библиотека `flag`, как я понимаю, не поддерживает  прямую обработку значений типа `time.Duration`.  

А если принимать строку и ее парсить, будет не по Т.З.

2024-07-04 06:36 UTC, AlexBlackNn commented on app/agent/restagentsender/v2/sender.go
> +						SetRetryMaxWaitTime(time.Duration(mhs.cfg.AgentRetryMaxWaitTime) * time.Second)
Done

2024-07-04 07:05 UTC, AlexBlackNn commented on pkg/storage/memstorage/mem_storage.go
> +				<-time.After(time.Duration(cfg.ServerStoreInterval) * time.Second)
Done

2024-07-04 07:11 UTC, AlexBlackNn commented on internal/handlers/v2/metrics_handlers.go
> +	ctx := context.Background()
Действительно. Перешел на
```
 ctx := r.Context() 
```

2024-07-04 07:14 UTC, AlexBlackNn commented on internal/handlers/v2/metrics_handlers.go
> +	ctx := context.Background()
Done

2024-07-04 07:20 UTC, tmvrus commented on app/agent/restagentsender/v2/sender.go
> +					if savedMetric.GetType() == "counter" {
я бы предложил что-то типа MetricTypeCounter/MetricTypeGauge

2024-07-04 07:23 UTC, AlexBlackNn commented on internal/config/configserver/config.go
> +// Config consists project settings
Done

2024-07-04 08:34 UTC, AlexBlackNn commented on app/agent/restagentsender/v2/sender.go
> +				go func(savedMetric models.MetricInteraction) {
Сделал ограничитель на кол-во запросов на агенте, используя https://pkg.go.dev/golang.org/x/time/rate . Но, надо еще и на сервере сделать ограничитель, ведь если агент будет от других разработчиков, нельзя гарантировать, что в нем будет сделан  rate limiter. Чтобы для сервера не делать велосипед, возьму отсюда https://github.com/go-chi/httprate

2024-07-04 08:41 UTC, AlexBlackNn commented on app/agent/restagentsender/v2/sender.go
> +					if savedMetric.GetType() == "counter" {
Заменил

2024-07-04 09:13 UTC, AlexBlackNn commented on pkg/storage/memstorage/mem_storage.go
> +				<-memStorage.saveChan
Идея, чтобы за запись метрик отвечало только одно место в коде. Теперь есть две задачи: 
1. Чтобы метрики собирались раз в определенное кол-во времени. Это получается должна быть независимая горутина, которая время от времени берет мапу, блокирует ее на время и сохраняет на диск, или как вариант делает копию  БД в памяти и пишет на диск. Тогда, блокировать запись в БД на время сохранения БД на диск не придется (что - то типо RDB у redis?).   
2. Чтобы метрики сохранялись синхронно (я так понял синхронно с обновлением данных). Тут нужно было как-то передать данные из горутины, которая отвечает за запись данных в БД в горутину, которая отвечает за сохранение на диск. Так как в го парадигма CSP, получается передать можно через канал. 
Ошибку в логи, видимо, добавлю не знаю как ее тут еще можно обработать, кроме логов. 

"запрос ведь все равно выполняется синхронно, так почему снаружи прост не дергать метод который все сохранит и обработает ошибку(которая сейчас никак не обрабатывается)?" Не совсем понял  твою задумку, напиши, пожалуйста, подробнее.

2024-07-05 06:38 UTC, AlexBlackNn commented on pkg/storage/memstorage/mem_storage.go
> +				<-memStorage.saveChan
Done

2024-07-05 07:20 UTC, AlexBlackNn commented on pkg/storage/memstorage/gob_state_manager.go
> +		_ = file.Close()
Done

2024-07-05 07:20 UTC, AlexBlackNn commented on pkg/storage/memstorage/gob_state_manager.go
> +		_ = file.Close()
Done

2024-07-05 07:20 UTC, AlexBlackNn commented on pkg/storage/memstorage/mem_storage.go
> +		_ = memStorage.jm.restoreMetrics()
Done

2024-07-05 08:33 UTC, AlexBlackNn commented on pkg/storage/memstorage/mem_storage.go
> +var ErrFailedToRestoreMetrics = errors.New("failed to restore metrics")
да, я думал сделать набор ошибок для storage и передавать на слой выше, но сейчас просто удалил.

2024-07-05 08:58 UTC, AlexBlackNn commented on internal/config/configserver/config.go
> +	}
Done

2024-07-05 09:00 UTC, AlexBlackNn commented on internal/config/configserver/config.go
> +		return &Config{}, config.ErrReadConfigFailed
Done

2024-07-05 09:15 UTC, AlexBlackNn commented on internal/handlers/v2/metrics_handlers.go
> +		if errors.Is(err, io.EOF) {
воспроизвести:

2024-07-05 12:36 UTC, AlexBlackNn commented on internal/handlers/v2/metrics_handlers_response.go
> +}
Добавил TestServerWrongType()

2024-07-08 06:18 UTC, tmvrus approved these changes

2024-07-08 06:18 UTC, tmvrus commented on pkg/storage/memstorage/mem_storage.go
> +				<-memStorage.saveChan
ты используешь канал для синхронизации там где она и так уже есть, это бессмысленно
торчат каналом наружу - из стораджа так себе практика, поскольку раскрывает детали реализации, детали эти вызывающему коду ничего не дают
у тебя есть задача - сохранить метрики, и два варианта - по таймеру, по вызову решается она созданием метода который делает сохранение и дергается либо вызывающим кодом, там где ты канал используешь, либо в цикле таймера

2024-07-08 10:34 UTC, merged