Iter13
AlexBlackNn/metrics pull request #15
Opened 2024-07-11 11:46 UTC by AlexBlackNn

2024-07-16 08:13 UTC, tmvrus requested changes

2024-07-16 08:13 UTC, tmvrus commented on app/agent/restagentsender/v3/sender.go
> +func (mhs *Sender) Send(ctx context.Context) {
в Go принято давать короткие имена "method receiver" это не ошибка конечно же, просто рекомендую следовать устоявшейся в языке практике

2024-07-16 08:13 UTC, tmvrus commented on app/agent/restagentsender/v3/sender.go
> +		default:
так работает, но выглядит не очень, default это инструмент когда "мы не знаем что сделать" в нашем случае код выполняет конкретное бизнес-действие, что бы это исправить можно использовать time.NewTimer это счетчик будет посылать сигнал каждую единицу времени и его можно использовать в блоке select, так код будет выглядеть более профессионально

2024-07-16 08:13 UTC, tmvrus commented on app/agent/restagentsender/v3/sender.go
> +					log.Error(err.Error())
вот тут разве не надо завершить работу? или попробовать continue

2024-07-16 08:13 UTC, tmvrus commented on app/agent/restagentsender/v3/sender.go
> +				log.Info("http request finished successfully",
тут есть противоречие, если была ошибка код все равно напечатает "http request finished successfully"

2024-07-16 08:13 UTC, tmvrus commented on app/agent/restagentsender/v3/sender.go
> +				body += "]"
Это не самый оптимальный способ превратить что-то в json, дело в том, что на каждой операции со строкой будет происходить выделение памяти, что бы эффективно работать со строками лучше использовать byte/string builder, тогда количество выделений памяти можно снизить.

не ясно, зачем каждую метрику заворачивать в json-список, `{}` - само по себе уже валидный JSON
если задача была послать несколько метрики одним запросом `[{},{},{}]` то тогда надо было делать это в конце цикла

2024-07-16 08:13 UTC, tmvrus commented on app/server/app.go
> +		log.Info("Finish to apply migrations")
тут видимо потерян return

2024-07-16 08:13 UTC, tmvrus commented on internal/handlers/v1/metrics_handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
return

2024-07-16 08:13 UTC, tmvrus commented on internal/handlers/v2/metrics_handlers.go
> +		if errors.As(err, &validateErr) {
а если там какая-то другая ошибка, код продолжит спокойно работать, кейс коечно маловероятный, но учесть его стоит

2024-07-16 08:13 UTC, tmvrus commented on internal/handlers/v2/metrics_handlers.go
> +		responseError(w, r, http.StatusInternalServerError, err.Error())
return?

2024-07-16 08:13 UTC, tmvrus commented on internal/handlers/v2/metrics_handlers.go
> +		}
тоже самое тут

2024-07-16 08:13 UTC, tmvrus commented on internal/handlers/v3/metrics_handlers.go
> +	err := render.DecodeJSON(r.Body, &reqMetrics)
вот тут ожидается что будет список метрик [{},{},{}] но выше, я отписал что он будет из 1 элемента что не очень логично

2024-07-16 08:13 UTC, tmvrus commented on internal/handlers/v3/metrics_handlers.go
> +	var severalMetrics []models.MetricInteraction
размер можно указать заранее, поскольку размер reqMetrics  известен

2024-07-16 08:13 UTC, tmvrus commented on internal/services/metricsservice/metric_service.go
> +	return err
не стоит так возвращать результат, лучше явным образом вернуть nil если ошибки не было, коллеги которые будут читать код скажут спасибо

2024-07-16 08:13 UTC, tmvrus commented on pkg/storage/memstorage/mem_storage.go
> +				storage.ErrMetricNotFound,
не стоит возвращать вместе ошибку и результат, это может сбить столку читателя

2024-07-16 08:13 UTC, tmvrus commented on pkg/storage/postgres/postgres.go
> +	`))
а есть смысл парсить это выражение каждый раз?

2024-07-17 13:45 UTC, AlexBlackNn commented on app/agent/restagentsender/v3/sender.go
> +func (mhs *Sender) Send(ctx context.Context) {
Done

2024-07-17 13:48 UTC, AlexBlackNn commented on app/agent/restagentsender/v3/sender.go
> +					log.Error(err.Error())
Надо, вижу что часто в проекте забываю про это. Спасибо

2024-07-17 14:37 UTC, AlexBlackNn commented on app/agent/restagentsender/v3/sender.go
> +				log.Info("http request finished successfully",
Done

2024-07-17 14:40 UTC, AlexBlackNn commented on internal/services/metricsservice/metric_service.go
> +	return err
Done

2024-07-17 14:47 UTC, AlexBlackNn commented on pkg/storage/memstorage/mem_storage.go
> +				storage.ErrMetricNotFound,
Done

2024-07-17 14:57 UTC, AlexBlackNn commented on internal/handlers/v2/metrics_handlers.go
> +		responseError(w, r, http.StatusInternalServerError, err.Error())
Done

2024-07-17 14:58 UTC, AlexBlackNn commented on internal/handlers/v1/metrics_handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Done

2024-07-17 18:31 UTC, AlexBlackNn commented on app/agent/restagentsender/v3/sender.go
> +		default:
Сделал через 	case <-time.After(reportInterval):

2024-07-17 19:40 UTC, AlexBlackNn commented on internal/handlers/v3/metrics_handlers.go
> +	var severalMetrics []models.MetricInteraction
Done

2024-07-18 11:11 UTC, AlexBlackNn commented on app/agent/restagentsender/v3/sender.go
> +				body += "]"
Done

2024-07-18 11:19 UTC, AlexBlackNn commented on internal/handlers/v2/metrics_handlers.go
> +		if errors.As(err, &validateErr) {
Done. Сделал 
```
responseError(w, r, http.StatusUnprocessableEntity, "failed to validate metric")
```

2024-07-18 11:19 UTC, AlexBlackNn commented on internal/handlers/v2/metrics_handlers.go
> +		}
Done. Сделал 
```
responseError(w, r, http.StatusUnprocessableEntity, "failed to validate metric")
```

2024-07-18 11:29 UTC, AlexBlackNn commented on internal/handlers/v3/metrics_handlers.go
> +	err := render.DecodeJSON(r.Body, &reqMetrics)
не понял тебя, почему ты полагаешь что тут будет список из 1 элемента, предпологается, что придет [{},{},{}]. Если это, ты про комментарий https://github.com/AlexBlackNn/metrics/pull/15#discussion_r1678934215, то да, там баг.  Предпологалась отправка  [{},{},{}]. Пофиксил

2024-07-18 16:06 UTC, AlexBlackNn commented on pkg/storage/postgres/postgres.go
> +	`))
Done

2024-07-22 15:50 UTC, tmvrus approved these changes
у easyjson есть хорошая альтернатива не требующая генерации кода, рекомендую ознакомиться
https://github.com/json-iterator/go

2024-09-17 16:36 UTC, merged