Iter15
AlexBlackNn/metrics pull request #17
Opened 2024-07-23 11:40 UTC by AlexBlackNn

2024-07-24 14:10 UTC, tmvrus requested changes
я нашел к чему придраться)

2024-07-24 14:10 UTC, tmvrus commented on app/server/app.go
> +			log.Error("Failed to apply migration", "err", err.Error())
а вот тут должен быть return

2024-07-24 14:10 UTC, tmvrus commented on internal/services/agentmetricsservice/monitor_service.go
> +				log.Error(err.Error())
continue?

2024-07-24 14:10 UTC, tmvrus commented on pkg/storage/postgres/postgres.go
> +	}(tx)
вот  это довольно спорный момент:
- какой смысл писать ошибку ролбека если эта ошибка дальше никуда не попадет
- если транзакция будет закомичена, Rollback вернет ошибку ErrTxClosed а она не нулевая

2024-07-24 14:10 UTC, tmvrus commented on pkg/storage/postgres/postgres.go
> +	sqlTmpStms[configserver.MetricTypeCounter] = "INSERT INTO app.counter_part (metric_id, name, value) VALUES ((SELECT uuid FROM app.types WHERE name = $1), $2, $3)"
учитывая что эти  stm не меняются, их вполне можно создавать при старте приложения и дальше пользоваться.

2024-07-24 14:10 UTC, tmvrus commented on pkg/storage/postgres/postgres.go
> +		//are closed by the call to Tx.Commit or Tx.Rollback. https://pkg.go.dev/database/sql#Tx
тут у тебя ссылка на стандартную либу, в проекте pgx совершенно не обязательно что он будет себя везти аналогично

2024-07-24 14:10 UTC, tmvrus commented on pkg/storage/postgres/postgres.go
> +		//are closed by the call to Tx.Commit or Tx.Rollback. https://pkg.go.dev/database/sql#Tx
я бы рекомендовал использовать pgx напрямую, раз уж он подключен

2024-07-30 06:11 UTC, AlexBlackNn commented on app/server/app.go
> +			log.Error("Failed to apply migration", "err", err.Error())
Сделал, там еще надо учесть, что в этой либе передают как ошибку, если миграций новых нет. https://github.com/golang-migrate/migrate/issues/100

2024-07-30 07:54 UTC, AlexBlackNn commented on app/server/app.go
> +			log.Error("Failed to apply migration", "err", err.Error())
Еще наткнулся на такую ошибку при запуске локальных тестов:  Dirty database version 1. Fix and force version. 
SELECT * FROM app.schema_migrations; 
и действительно в поле dirty стоит true
Что странно так как новые миграции не накатываются.

2024-07-30 08:04 UTC, AlexBlackNn commented on internal/services/agentmetricsservice/monitor_service.go
> +				log.Error(err.Error())
Done

2024-07-30 08:31 UTC, AlexBlackNn commented on pkg/storage/postgres/postgres.go
> +		//are closed by the call to Tx.Commit or Tx.Rollback. https://pkg.go.dev/database/sql#Tx
> тут у тебя ссылка на стандартную либу, в проекте pgx совершенно не обязательно что он будет себя везти аналогично

Удалил комментарий, пока сходу не нашел что делает pgx. Посмотрел в коде, у меня кстати Коммит и Ролбэк присутствуют все равно. Я бы сказал, что коммент еще и путал

2024-07-30 08:32 UTC, AlexBlackNn commented on pkg/storage/postgres/postgres.go
> +		//are closed by the call to Tx.Commit or Tx.Rollback. https://pkg.go.dev/database/sql#Tx
> я бы рекомендовал использовать pgx напрямую, раз уж он подключен

Пока решил оставить, чтобы было если что удобнее переходить на другие БД. Тут стоит подумать над функциональностью pgx, которой нет в database/sql и нужна ли она в данном сервисе.

2024-07-30 08:46 UTC, AlexBlackNn commented on pkg/storage/postgres/postgres.go
> +	}(tx)
Я думал, если честно, она должна была быть проброшена на сервисный слой и там обработана. Вот тут https://github.com/AlexBlackNn/metrics/blob/d8e33298af5216d9e83016532a5b6f01a7313fdc/internal/services/metricsservice/metric_service.go#L147 (сейчас там действительно нет обработки ошибки ErrTxClosed)

2024-07-30 08:48 UTC, AlexBlackNn commented on pkg/storage/postgres/postgres.go
> +	}(tx)
Убрал, добавление ошибки от tx.Rollback()

2024-07-30 09:01 UTC, AlexBlackNn commented on pkg/storage/postgres/postgres.go
> +	sqlTmpStms[configserver.MetricTypeCounter] = "INSERT INTO app.counter_part (metric_id, name, value) VALUES ((SELECT uuid FROM app.types WHERE name = $1), $2, $3)"
А они же по коду сейчас живут внутри транзакции.

2024-07-30 09:21 UTC, AlexBlackNn commented on pkg/storage/postgres/postgres.go
> +		//are closed by the call to Tx.Commit or Tx.Rollback. https://pkg.go.dev/database/sql#Tx
> тут у тебя ссылка на стандартную либу, в проекте pgx совершенно не обязательно что он будет себя везти аналогично

Пока не нашел подтверждение для pgx закрываю в коде

2024-09-17 16:36 UTC, merged

2024-09-17 16:37 UTC, AlexBlackNn commented
done