Iter5
AlexBlackNn/metrics pull request #6
Opened 2024-06-09 06:37 UTC by AlexBlackNn

2024-06-13 12:53 UTC, capsulated requested changes
Читай коменты, плюс сейчас созвонимся 1-1

2024-06-13 12:53 UTC, capsulated commented on cmd/server/main.go
> +func NewChiRouter(log *slog.Logger, application *appserver.App) chi.Router {
Роутер надо убрать в отдельный пакет, так как в `cmd` должен быть только запуск программы

2024-06-13 12:53 UTC, capsulated commented on internal/appserver/app.go
> +type App struct {
Для типа `App` лучше создать пакет `app`, рядом с `cmd`

2024-06-13 12:53 UTC, capsulated commented on internal/config/config.go
> +func Load() (*Config, error) {
Это получается стандартный [конструктор](https://go.dev/doc/effective_go#composite_literals) 
```go
func New() (*Config, error) { ... }
```

2024-06-13 12:53 UTC, capsulated commented on cmd/agent/main.go
> +		appHTTP.MetricsService.Start(cancel)
В данном случае, на мой взгляд, удобнее использовать контекст с отменой, нежели канал. В общем, идея правильная, это по сути graceful shotdown получается. Часто используется просто select с чтением канала с сигналами  и switch для определения, что за сигнал ОС пришел

2024-06-13 12:53 UTC, capsulated commented on cmd/server/main.go
> +	log := utils.SetupLogger(cfg.Env)
`utils` плохой нейминг. Лучше сразу создать пакет для логгера с интерфейсом. И та же история с именем конструктора: `logger.New(cfg)`

2024-06-13 12:53 UTC, capsulated commented on cmd/server/main.go
> +	router := NewChiRouter(log, application)
Вызов конструктора роутера тогда уже внутри конструктора приложения appserver запускать лучше?

2024-06-13 12:53 UTC, capsulated commented on cmd/server/main.go
> +	router := NewChiRouter(log, application)
Посмотрел appserver - это получилась простая обёртка над `metricsService`. Мне кажется тут можно просто создать `metricsService` без дополнительного объекта application

2024-06-13 12:53 UTC, capsulated commented on internal/appagent/app.go
> +	metricsService := agenthttp.New(
`agenthttp.New()` должен вернуть указатель на экземпляр `*agentHttp`

2024-06-13 12:53 UTC, capsulated commented on internal/domain/models/metric.go
> +	case reflect.Float64:
А надо ли рефлексию использовать в данном случае? В рантайме она не дешевая. Нам заранее известны типы метрик, их всего два. Самый простой вариант - использовать две мапы с нужными типами. Посложнее - дженерики. А рефлексию лучше при кодогенерации использовать, а не в рантайме

2024-06-13 12:53 UTC, capsulated commented on internal/domain/models/metric.go
> +	if metricType != "gauge" && metricType != "counter" {
Это и есть `по факту` дженерик

2024-06-13 12:53 UTC, capsulated commented on internal/domain/models/metric.go
> +	} else if metricType == "counter" {
Очень неудобная для чтения конструкция, много if else, лучше упростить, лучше даже с дублированием return Metric{...}. И возвращать лучше указатель *Metric, в случае ошибки будет `return nil, ErrNotValidMetricValue

2024-06-13 12:53 UTC, capsulated commented on internal/http-server/v1/metrics/getallmetrics/get_all_metrics.go
`v1` пакет точно нужен? Вообще очень большая вложенность. В go папка - это уже синтаксис языка, в начале каждого файла мы пишем `package name`, что является аналогом namespace из некоторых других ЯП. Создав папку мы автоматически создаём пакет в go

2024-06-13 12:53 UTC, capsulated commented on internal/http-server/v1/metrics/getallmetrics/get_all_metrics.go
> +func New(log *slog.Logger, application *appserver.App) http.HandlerFunc {
У каждого хендлера отедльный пакет - мне кажется это многовато. Можно все хендлеры положить в один пакет на в разных файлах. И нейминг `New` заменить. Но лучше всего, описать отдельный структурный тип для хендлеров, что-то типа `Handlers` или `HandlerWorker`, ему в конструктор передавать все необходимые зависимости (log, application и тп) и роутеру уже передавать методы типа: `handlers.GetAllMetrics`. Профит в управлении зависимостями

2024-06-13 12:53 UTC, capsulated commented on internal/services/agentmetricsservice/monitor.go
> +func New(
`New` должен вернуть `*Monitor`. Если это не так, то конструктор необходимо назвать `NewMetricsService(...)`

2024-06-13 12:53 UTC, capsulated commented on internal/services/agentmetricsservice/monitor.go
> +			t := reflect.TypeOf(rtm)
Рефлект нинада

2024-06-13 12:53 UTC, capsulated commented on internal/services/metricsservice/metrics_service.go
> +type MetricsStorageInterface interface {
Про нейминг интерфейсов в go читать [тут](https://go.dev/doc/effective_go#interface-names)

2024-06-13 12:53 UTC, capsulated commented on internal/transport/agenthttp/transmitter.go
> +type HTTPService struct {
Нейминг не очень хороший. И не могу никак разобраться, может можно этот функционал реализовать внутри agentmetricsservice?

2024-06-13 12:53 UTC, capsulated commented on pkg/storage/memstorage/mem_storage.go
> +	case <-ctx.Done():
Что-то меня смущают select'ы в каждом методе. Контекст в методах с работой с памятью они точно нужен? В задании этого не было, если и усложнять себе жизнь дополнительным функционалом, то тогда надо это реализовать правильно

2024-06-13 12:53 UTC, capsulated commented on statictest
бинарники в репозиторий не комитят, плохая примета 😄

2024-06-13 14:52 UTC, AlexBlackNn commented on cmd/server/main.go
> +	log := utils.SetupLogger(cfg.Env)
в логгер папку

2024-06-13 14:56 UTC, AlexBlackNn commented on cmd/server/main.go
> +	router := NewChiRouter(log, application)
Решили перенести App в cmd (настройка всего приложения)

2024-06-15 06:33 UTC, AlexBlackNn commented on cmd/server/main.go
> +func NewChiRouter(log *slog.Logger, application *appserver.App) chi.Router {
Done

2024-06-15 06:33 UTC, AlexBlackNn commented on internal/appserver/app.go
> +type App struct {
Done

2024-06-15 06:45 UTC, AlexBlackNn commented on internal/config/config.go
> +func Load() (*Config, error) {
Done

2024-06-15 06:59 UTC, AlexBlackNn commented on internal/services/metricsservice/metrics_service.go
> +type MetricsStorageInterface interface {
По твоей ссылке рекомендашка только об именовании интерфейсов, состоящих из 1 метода. 
https://go.dev/talks/2014/names.slide#13 
Вот тут нашел: When an interface includes multiple methods, choose a name that accurately describes its purpose (examples: net.Conn, http.ResponseWriter, io.ReadWriter).

2024-06-15 07:06 UTC, AlexBlackNn commented on statictest
Done

2024-06-15 07:30 UTC, AlexBlackNn commented on internal/http-server/v1/metrics/getallmetrics/get_all_metrics.go
v1 считаю нужным, если вдруг будет следующая версия API. Убрал немного вложенности за счет создание 1 стрктуры, к которой привязал хэндлеры методами (как обсудили на созвоне)

2024-06-15 07:36 UTC, AlexBlackNn commented on internal/http-server/v1/metrics/getallmetrics/get_all_metrics.go
> +func New(log *slog.Logger, application *appserver.App) http.HandlerFunc {
Done

2024-06-16 07:52 UTC, AlexBlackNn commented on internal/domain/models/metric.go
> +	case reflect.Float64:
Переписал через дженерики

2024-06-16 08:02 UTC, AlexBlackNn commented on internal/domain/models/metric.go
> +	} else if metricType == "counter" {
Done

2024-06-16 08:20 UTC, AlexBlackNn commented on internal/transport/agenthttp/transmitter.go
> +type HTTPService struct {
Вынес из agentmetricsservice, чтобы можно было гибко настраивать отправку (rest, grpc, brokers). Переназвал на Transport -> Sender, Transmitter -> Sender. agentttp ->  restagentsender. 
Идея в следующем: restagentsender.New(...) создает структуру для передачи метрик по rest. Если потребуется передавать по другому может появиться:
grpcagentsender.New(...)
kafkaagentsender.New(...)

2024-06-16 09:40 UTC, AlexBlackNn commented on pkg/storage/memstorage/mem_storage.go
> +	case <-ctx.Done():
да, а если по какой то причине, начнем SLA не выполнять? Плюс, при переходе к SQL/ NOSQL хранилищам тоже потребуется. 
А правильная реализация, какая?  Вот тут есть реализация для обработки Deadline контекста (для примера)  
https://github.com/golang/go/blob/fe36ce669c1a452d2b0e81108a7e07674b50692a/src/database/sql/sql.go#L1308
Удалил  разве что с сервисного слоя и прокидываю сейчас контекст в storage

2024-06-16 10:15 UTC, AlexBlackNn commented on cmd/agent/main.go
> +		appHTTP.MetricsService.Start(cancel)
Переписал через контекст, за основу взял https://medium.com/@matryer/make-ctrl-c-cancel-the-context-context-bd006a8ad6ff

2024-06-16 10:28 UTC, AlexBlackNn commented on internal/services/agentmetricsservice/monitor.go
> +func New(
Сделал MonitorService и переименовал файл в monitor_service.go

2024-06-16 11:34 UTC, AlexBlackNn commented on internal/services/agentmetricsservice/monitor.go
> +			t := reflect.TypeOf(rtm)
Done

2024-06-17 16:20 UTC, capsulated requested changes
По организации папок, по-прежнему, замечания. Так же по context. И организацию объектов нужны доработки по неймингу и удалению лишних абстракций

2024-06-17 16:20 UTC, capsulated commented on cmd/appagent/app.go
> +type AgentService interface {
Так, опять описание интерфейсов, типов и конструкторов в `cmd`. 

"Для типа App лучше создать пакет app, рядом с cmd"(c) - это на том же уровне, что и cmd:
```
/metrics
- /app
---- /server
---- /agent 
- /cmd
---- /server
---- /agent 
....
- /internal
- /pkg
```

2024-06-17 16:20 UTC, capsulated commented on cmd/appagent/app.go
> +type AppHTTP struct {
1. И всё же, зачем 'обёртка' над `MetricsService`? И так есть ссылки на логер и конфиг в типе `metricsService`, зачем ещё создавать тип, в котором только одно поле MetricsService? Необходимо просто для типа MetricsService добавить конструктор `New(log *slog.Logger, cfg *config.Config) *MetricService`, а AppHTTP явно лишний, так как всего один воркер
2. И почему поле структуру имеет тип интерфейса?  Нейминг очень сбивает с толку. Реализация сервиса одна единственная, поэтому интерфейс заранее описывать не надо (это ещё одна правила о том, что интерфейсы описываются в местах использования)

2024-06-17 16:20 UTC, capsulated commented on cmd/router/chi_router.go
> +func NewChiRouter(log *slog.Logger, m v1.Metrics) chi.Router {
Возвращаемый тип лучше описать указателем на тип

2024-06-17 16:20 UTC, capsulated commented on cmd/server/main.go
> +	application := appserver.New(log, cfg)
Тога внутри конструктора application должны быть вызовы всех конструкторов объектов. А в cmd только Run или ListenAndServe и тп

2024-06-17 16:20 UTC, capsulated commented on internal/api/metrics/v1/metrics.go
`internal/api/metrics/v1/metrics.go` очень большая вложенность. И совсем не понятно, что за типы объектов?Если это хендлеры, почему бы их не создать в корне, к примеру `internal/handlers`? И `v1` сразу скажу, в течение курса не понадобится, только усложняет жизнь

2024-06-17 16:20 UTC, capsulated commented on internal/api/metrics/v1/metrics.go
> +func New(log *slog.Logger, application *appserver.App) Metrics {
Когда возвращать по указателю, а когда по значению? А когда интерфейс? ) Первый вопрос - обязательный для изучения и понимания

2024-06-17 16:20 UTC, capsulated commented on internal/api/metrics/v1/metrics.go
> +type Metrics struct {
Совершенно непонятно, что за объект и зачем он ((( MetricService был уже. Всё же это http хендлеры, нужно как-то это использовать в имени

2024-06-17 16:20 UTC, capsulated commented on internal/api/metrics/v1/metrics.go
> +	for _, metric := range metrics {
Подготавливать данные необходимо в сервисном слое, из хендлеров лучше перенести. Это может быть либо на уровне хранилки, либо доп объект, типа `ХранилкаСервис`, с финальными методами, которые обращаются к методам контроллеру хранилки (уже простые sql SELECT, UPDATE, DELETE) а далее  преобразовывает и возвращает уже подготовленные данные в нужном виде

2024-06-17 16:20 UTC, capsulated commented on internal/api/middleware/logger/logger.go
> +package logger
Из логгера так и не убрал. В этот middleware внедряется зависимость на логгер, а не наоборот. 

Приводил пример с https://github.com/go-chi/chi - посмотри как реализованы middleware. Должно быть что-то типа того `/internal/middleware/logger.go`

2024-06-17 16:20 UTC, capsulated commented on internal/domain/models/metric.go
> +type Metric[T constraints.Integer | constraints.Float] struct {
Тип Mertic уже был выше. Хотя правильный этот.

Дженерики ок, но ещё раз повторюсь: зачем выбирать сложные вариант, когда есть простые? В проде это плохо заканчивается, эксперименты нужно делать в свободное от основной ветки разработки

2024-06-17 16:20 UTC, capsulated commented on internal/domain/models/metric.go
> +	return m.Type
Вообще не вижу смысла, так как интерфейс, описанный выше, не требуется.

2024-06-17 16:20 UTC, capsulated commented on internal/domain/models/metric.go
> +type MetricInteraction interface {
Ох, а зачем интерфейс тут? Ещё и с геттерами/сеттерами? Это лишнее

2024-06-17 16:20 UTC, capsulated commented on internal/domain/models/metric.go
> +type MetricInteraction interface {
А, ещё описан интерфейс в месте реализации. А нужно в месте использования

2024-06-17 16:20 UTC, capsulated commented on internal/domain/models/metric.go
> +func Load(metricType string, metricName string, metricValue string) (MetricInteraction, error) {
А это не метод хранилки должен быть?
```go
func (*Storage) SaveMetric() {}
func  (*Storage) GetMetric() {}
...
```

2024-06-17 16:20 UTC, capsulated commented on internal/sender/restagentsender/sender.go
> +type Sender struct {
Тоже лишняя структура. Это же метод агнета

2024-06-17 16:20 UTC, capsulated commented on internal/services/agentmetricsservice/monitor_service.go
> +type MonitorService struct {
Можно даже `Service` убрать. В данном контексте `Monitor` подходящий нейминг. `MetricsCollector`, `MetricScraper` и тп как альтернативы

2024-06-17 16:20 UTC, capsulated commented on internal/services/metricsservice/metric_service.go
> +type MetricService struct {
Ещё один слой, который очень сильно запутывает.  У самого домена Metric есть какие-то методы, есть MetricService, который не ясно, относиться к агенту, серверу или к тому и другому. может их как-то разделить? Или просто уточнить в нейминге? Но много слов в имени тоже не очень хорошо, лучше одно-два слова, но однозначно обозначающий функционал

2024-06-17 16:20 UTC, capsulated commented on pkg/storage/memstorage/mem_storage.go
> +	case <-ctx.Done():
Подключение управляется на уровне драйвера, а не в собственных методах. В примере что на выходе метода? А в данном методе вообще запись в память.

Создай нагрузочный тест и вообще посмотри, за какой время исполняется работа данного метода и сопоставь с тем временем таймаута. 

Тем более, в задании такого нет. Какой таймаут? Какая вероятность этого таймаута? Тогда нужно отменять запись в мапу - ну это очень странная история

Если коротко - это лишнее

2024-06-17 17:29 UTC, AlexBlackNn commented on pkg/storage/memstorage/mem_storage.go
> +	case <-ctx.Done():
можно было бы попробовать, на Locust как раз недавно делал. Мне кажется, что за счет мьютекса, там все же будет узкое место и при высоком rps это будет видно.
Сейчас проще убрать)

2024-06-17 17:37 UTC, AlexBlackNn commented on internal/domain/models/metric.go
> +	if metricType != "gauge" && metricType != "counter" {
Done

2024-06-17 18:30 UTC, AlexBlackNn commented on internal/domain/models/metric.go
> +type MetricInteraction interface {
1. Про интерфейс обсуждаем в пачке. 
2. Мне тоже нравится в месте реализации больше. Посмотрел видео про чистую архитектуру, там в домейн областе спикер писал интерфейс, на его волне повторил. https://www.youtube.com/watch?v=eVhIlhLl4e4. Поправил

2024-06-19 12:56 UTC, capsulated approved these changes
Необходимо учесть новые комментарии в следующем спринте.

Самое главное замечание - не надо делать то, чего не было в задании. В рамках курса всё успеем разобрать. Собственное творчество сможем применить в выпускных работах. Не следует добавлять сторонние фичи, чтобы не увеличивать время разработки и проверки себе и ментору. В коммерческой разработке это будет очень сильно мешать, так как бизнесу интересен стабильный, быстро написынный код, реализующий функционал ТЗ, а принципы программирования, чистый код и тп - к сожалению нет, нужно держать балланс

2024-06-19 12:56 UTC, capsulated commented on app/agent/restagentsender/sender.go
> +package restagentsender
Если добавил, всё же, `app` пакет, то тогда в нём собираетсся приложение из конструкторов. Бизнес логики также тут быть не должно. Надо перенести `sender` в `internal` или в корень проекта

2024-06-19 12:56 UTC, capsulated commented on app/agent/restagentsender/sender.go
> +func (mhs *Sender) Send(ctx context.Context) {
Имя переменной для ресивера сильно отличается от имени типа, может запутать

2024-06-19 12:56 UTC, capsulated commented on app/agent/app.go
> +type CollectSender interface {
По интерфейсам, ещё раз повторюсь: если есть только одна реализация, то интерфейс не нужен и описывать его не надо. Только в том случае, если появляется вторая реализация (или более), только тогда необходим интерфейс. Иначе - ненужное усложнение и лишний код

2024-06-19 12:56 UTC, capsulated commented on cmd/config/local.yaml
Конфига в задании же ещё нет. Вообще нет ни одного пункта в ТЗ с чтением конфигов. Это будут следующие спринты (с дженериками та же история).  При работе с ТЗ инкрементов я не советую добавлять собственные фичи, как в pet проекте. Но не беспокойся, этим ещё успеем позаниматься на выпускных проектах. В рамках инкременов добавление лишнего функционала - это ошибка, так как это только "нагромождает" проект, время написания, проверки и сдачи. Есть ТЗ и автотесты - и только на них необходимо ориентироваться в рамках инкрементов

2024-06-19 12:56 UTC, capsulated commented on cmd/server/main.go
> +	application, err := server.New()
Конструктор `сервер`, а имя новой переменной - `приложение`. Очень советую называть практически одинаково переменные на всех уровнях абстракции, чтобы в дальнейшем не было путаницы

2024-06-19 12:56 UTC, capsulated commented on internal/domain/models/metric.go
> +type MetricInteraction interface {
Как и разобрались в чате, объявить слайс дженерик типа нельзя, а интерфейс можно. Тут ок. Но всегда следи за тем, что ко всему подряд интерфейсы описывать не нужно (практика 'на потом' - плохая практика). Как только появляется две реализации, только тогда необходимо описать интерфейс.

2024-06-19 12:56 UTC, capsulated commented on internal/middleware/logger.go
> +package middleware
миддлварь, ок 👍

Но! Опять же, эти задания будут только в следующих инкрементах. Не надо делать то, чего нет в задании. Если в процессе реализации ТЗ тебе именно потребовался этот функционал (к примеру, для отладки, так как было что-то непонятно), тогда ок. Но не нужно лишние фичи добавлять в инкременты, повторюсь, успеешь этим позаниматься на двух выпускных проектах. В инкрементах не советую - есть вероятность самому в дедлайны не вписаться и ментору дополнительные сложности создашь

2024-06-19 17:20 UTC, merged